### ISSUE TITLE
200 OK error in  Flarum 0.1.0-beta.16

### ISSUE THREAD

**Issue by s1-ranjan** [eddiewebb/flarum-gpx-preview#2]
I tried to install this plugin in a fresh install of Flarum but it gave the following error

POST http://localhost/flarum/api/fof/upload

<br />
<b>Warning</b>:  preg_match(): Unknown modifier 'g' in <b>/var/www/flarum/vendor/fof/upload/src/Commands/UploadHandler.php</b> on line <b>204</b><br />
<br />
<b>Fatal error</b>:  Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /var/www/flarum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:24
Stack trace:
#0 /var/www/flarum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent()
#1 /var/www/flarum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;assertNoPreviousOutput()
#2 /var/www/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;emit(Object(Flarum\Api\JsonApiResponse))
#3 /var/www/flarum/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner-&gt;run()
#4 /var/www/flarum/index.php(26): Flarum\Http\Server-&gt;listen()
#5 {main}
  thrown in <b>/var/www/flarum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php</b> on line <b>24</b><br />

**Comment by s1-ranjan** [comment]
After trying various combinations, I am finally able to upload .gpx file in my local environment but, this uploaded file is shown in the link format, so I am wondering is there any specific code that is required to render the map

**Comment by eddiewebb** [comment]
not sure about the firs terror as that is in fof/upload, but looks like a bad Regexp in your settings.

As for the gpx-preview, make sure you're on `v0.2.4` and have provided API key in the admin settings.

Check JS console for error output if still nto working.

**Comment by s1-ranjan** [comment]
I created Maps JavaScript API and plugged those values in the settings but till now no luck and in the java console, I don't find any error. I am including the screenshot of the images
![Screenshot_2021-04-18 Screenshot](https://user-images.githubusercontent.com/20767253/115131658-6ab6f800-a017-11eb-99bf-1aeaccc5e7a3.png)
input and output from the frontend is as follows
![gps](https://user-images.githubusercontent.com/20767253/115131680-a9e54900-a017-11eb-9887-33a06463c397.png)
and moreover, I am using flarum 0.1.0-beta.16

**Comment by eddiewebb** [comment]
2 issues I see.

1) you can google how various browswers attempt to read mime-type, but the end result is few handle GPX well and more usually are uplaoded as just xml, not gpx+xml :(

sio change regexp to be `^application\/.*xml`


2) the plugin works with upload plugin that creates special tags for the URL.
The screen you show looks like plain URL, doesn;t look like the file was added via upload plugin.  In order for the frontend map js to work, the actual URL should look more like this in raw/editing format:

`[upl-file uuid=3794ec1d-d1f8-4a44-8b7e-e06624da6226 size=113kB url=https://adkadv.com/assets/files/2020-10-13/1602614611-976951-kush-onchiotadetoured.gpx]kush-onchiotadetoured.gpx[/upl-file]`

**Comment by s1-ranjan** [comment]
Regarding the first issue, I made the correction as you suggested to change regexp values to ^application\/.*xml,  but when I tried to upload a gpx file it convert the file in the .XML format, so in order to upload the correct file format i.e., in gpx format I made a small modification in fof/uploas setting by making an entry under the user-provided file extinction this help me to successfully upload the gpx file.
well regarding the second part when I make a selection for gpx file from my media library it simply inserts the file URL rather than the actual format.
I am not sure what is wrong with my setup.

**Comment by s1-ranjan** [comment]
I personally feel that there is some issue between the upload and gpx plugin or gpx plugin is simply accepting Just URL setting for the gpx rather than the GPX route preview, please have a look in the bellow image.

![Screenshot from 2021-04-19 22-40-56](https://user-images.githubusercontent.com/20767253/115276255-7104bb80-a160-11eb-99e0-af1692d886fb.png)

**Comment by eddiewebb** [comment]
I'm not sure what you mean by the last photo, but the gpx plugin extends the upload plugin by adding another template option to render (which is what you see in dropdown). 

You need to make sure the mime-type is set to xml (looks correct) and that it adds the `gpx` as a `user provided file extensions` extension (which you did).

If this works you should be able to drag a gpx file into the editor and upload plugin will  convert to the template you specified, in our case the syntax I shared earlier.   Upload is the extension that handles the upload, and converts it.  I am not sure if the new media manager in 16 triggers the same logic. So it might be missing that logic altogether,  Try putting the `...*.xml` to another template type to isolate.

--- Edit ---

I am able to re-create but changing templates, for whatever reason fof/upload seems to no longer apply the template. I am looking through recent changes on their side but architecture looks the same.  I'll need to engage them to understand this..

**Comment by eddiewebb** [comment]
it is the media manager, they wrote a rather brute switch that exludes extensions ,... https://github.com/FriendsOfFlarum/upload/pull/262

**Comment by eddiewebb** [comment]
@s1-ranjan - give `v0.2.5` (from #3) a test please. It should work-around limitation while I hope fof team considers change. 

`composer require webbinaro/gpx-preview:v0.2.5`

It's fixed the issue for me locally and I just pushed to my own forum 🤞

**Comment by s1-ranjan** [comment]
Thanks for fixing this issue it is working normally for the forum part but it's not working with the blog plugin.

**Comment by eddiewebb** [comment]
> Thanks for fixing this issue it is working normally for the forum part but it's not working with the blog plugin.

V17's blog?

Are you getting specific behavior?  I know blog uses a modified editor, but the "Upload" biutton worked same for me.

![Screen Shot 2021-05-05 at 2 14 04 PM](https://user-images.githubusercontent.com/5262154/117189870-accc9180-adac-11eb-9fb1-07dff4455402.png)


![Screen Shot 2021-05-05 at 2 14 58 PM](https://user-images.githubusercontent.com/5262154/117189859-a9390a80-adac-11eb-8f16-a9e406874838.png)

**Comment by s1-ranjan** [comment]
Thanks, it working normally
